package frc.robot.subsystems.drive;

import static edu.wpi.first.units.Units.*;
import frc.lib.util.Capture;

import java.util.Optional;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;

import choreo.trajectory.SwerveSample;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.Vector;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N2;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.trajectory.TrapezoidProfile;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.button.Trigger;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.lib.util.DriveUtil;
import frc.robot.subsystems.drive.TunerConstants.TunerSwerveDrivetrain;

import frc.robot.Constants;


/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;

    private final SwerveRequest.ApplyRobotSpeeds pathApplyRobotSpeeds =
        new SwerveRequest.ApplyRobotSpeeds();

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }
    /**
     * Return our pose2d from our commandswervedrivetrain
     * 
     * @return the pose in two dimensions
     *      
     */
    public Pose2d getPose() {
        return getState().Pose;
    }

    //A couple variables for the pose tolerance in degrees
    //TODO see if these work for our robot
    public double toleranceMeters = Units.inchesToMeters(0.5);
    public double toleranceRadians = Units.degreesToRadians(1);


    private boolean withinTolerance(Rotation2d lhs, Rotation2d rhs, double toleranceRadians) {
        if (Math.abs(toleranceRadians) > Math.PI) {
            return true;
        }
        double dot = lhs.getCos() * rhs.getCos() + lhs.getSin() * rhs.getSin();
        // cos(θ) >= cos(tolerance) means |θ| <= tolerance, for tolerance in [-pi, pi],
        // as pre-checked
        // above.
        return dot > Math.cos(toleranceRadians);
    }

    public Trigger atPose(
            Supplier<Pose2d> poseSup, double toleranceMeters, double toleranceRadians) {
        return new Trigger(() -> {
            Pose2d pose = poseSup.get();
            Pose2d currentPose = getPose();
            boolean transValid = currentPose.getTranslation().getDistance(pose.getTranslation())
                    < toleranceMeters;
            boolean rotValid = withinTolerance(
                    currentPose.getRotation(), pose.getRotation(), toleranceRadians);
            return transValid && rotValid;
        });
    }
    /**
     * Return our heading from a Pose2d
     * 
     * @return the rotation of the bot as a rotation2d object
     */
    public Rotation2d getHeading() {
        return getPose().getRotation();
    }
    /**
     * Return our speeds as a chassis speeds object
     * 
     * @return the speeds of our robot as a chassis speeds object.
     */
    public ChassisSpeeds getSpeeds() {
        return getState().Speeds;
    }
    public ChassisSpeeds getFieldSpeeds() {
        return ChassisSpeeds.fromRobotRelativeSpeeds(getSpeeds(), getHeading());
    }
    private final PIDController trajectoryXController = new PIDController(14, 0, 0);
    private final PIDController trajectoryYController = new PIDController(14, 0, 0);
    private final PIDController trajectoryThetaController = new PIDController(3, 0, 0);

    private final SwerveRequest.ApplyFieldSpeeds trajectoryApplyFieldSpeeds =
            new SwerveRequest.ApplyFieldSpeeds()
                    .withDriveRequestType(SwerveModule.DriveRequestType.Velocity);

    //TODO Figure out how this works and add documentation
    public void followTrajectory(SwerveSample sample) {

        trajectoryThetaController.enableContinuousInput(-Math.PI, Math.PI);
        var pose = getState().Pose;
        var targetSpeeds = sample.getChassisSpeeds();
        targetSpeeds.vxMetersPerSecond += trajectoryXController.calculate(pose.getX(), sample.x);
        targetSpeeds.vyMetersPerSecond += trajectoryYController.calculate(pose.getY(), sample.y);
        targetSpeeds.omegaRadiansPerSecond += trajectoryThetaController.calculate(
                pose.getRotation().getRadians(), sample.heading);

        setControl(trajectoryApplyFieldSpeeds
                .withSpeeds(targetSpeeds)
                .withSpeeds(targetSpeeds)
                .withWheelForceFeedforwardsX(sample.moduleForcesX())
                .withWheelForceFeedforwardsY(sample.moduleForcesY()));
    }
    private TrapezoidProfile.Constraints driveToPoseConstraints =
            new TrapezoidProfile.Constraints(1, 1);
    private TrapezoidProfile.Constraints driveToPoseRotationConstraints =
            new TrapezoidProfile.Constraints(3, 6);
    private TrapezoidProfile driveToPoseProfile = new TrapezoidProfile(driveToPoseConstraints);
    private TrapezoidProfile driveToPoseRotationProfile =
            new TrapezoidProfile(driveToPoseRotationConstraints);

    // For modifying goals from within a lambda

    private TrapezoidProfile.State driveToPoseGoal = new TrapezoidProfile.State(0, 0);
    private TrapezoidProfile.State driveToPoseRotationGoal = new TrapezoidProfile.State(0, 0);

    Capture<Pose2d> initial = new Capture<Pose2d>(new Pose2d());
    // The goal (populated from poseSupplier at command start)
    Capture<Pose2d> goal = new Capture<Pose2d>(new Pose2d());
    // Distance start-end in meters
    Capture<Double> distance = new Capture<Double>(1.0);
    // Unit vector start->end
    Capture<Translation2d> normDirStartToEnd = new Capture<>(Translation2d.kZero);
    Capture<Vector<N2>> directionGoalToBot = new Capture<>(VecBuilder.fill(0, 0));
    TrapezoidProfile.State translationState = new TrapezoidProfile.State(0, 0);
    TrapezoidProfile.State rotationState = new TrapezoidProfile.State(0, 0);

    // Threshold for "close enough" to avoid microadjustments
    public final Trigger atDriveToPosePose =
            atPose(() -> goal.inner, Units.inchesToMeters(0.5), Units.degreesToRadians(1));
    public Command driveToPose(Supplier<Pose2d> poseSupplier) {
        Command command = runOnce(() -> {
                    var getTargetTime = Timer.getFPGATimestamp();

                    initial.inner = getPose();
                    goal.inner = poseSupplier.get();

                    // initial position: distance from end
                    // initial velocity: component of velocity away from end, so
                    // approaching is a negative number
                    var goalToBot = initial.inner.minus(goal.inner);
                    var directionGoalToBot =
                            goalToBot.getTranslation().toVector().unit();

                    this.directionGoalToBot.inner = directionGoalToBot;
                    // TODO: The bellow being commented out means that there is no
                    // velocity feedforward
                    //
                    // this.normDirStartToEnd.inner = new
                    // Translation2d(directionGoalToBot);

                    distance.inner = goalToBot.getTranslation().getNorm();

                    // Position goes from our distance to zero as we approach
                    translationState.position = distance.inner;

                    var speeds = getFieldSpeeds();

                    // A negative velocity means we are approaching 0, the goal is 0
                    translationState.velocity = MathUtil.clamp(
                            VecBuilder.fill(speeds.vxMetersPerSecond, speeds.vyMetersPerSecond)
                                    .dot(directionGoalToBot),
                            -driveToPoseConstraints.maxVelocity,
                            0);

                    // Initial state of rotation
                    driveToPoseRotationGoal.position = goal.inner.getRotation().getRadians();

                    rotationState.position = initial.inner.getRotation().getRadians();
                    rotationState.velocity = speeds.omegaRadiansPerSecond;

                })
                .andThen(run(() -> {
                    var setpoint = driveToPoseProfile.calculate(
                            Constants.LOOP_PERIOD_SEC, translationState, driveToPoseGoal);
                    translationState.position = setpoint.position;
                    translationState.velocity = setpoint.velocity;


                    // I am trusting them here

                    // Rotation continuous input
                    // Get error which is the smallest distance between goal
                    // and measurement
                    double errorBound = Math.PI;
                    var measurement = getHeading().getRadians();
                    double goalMinDistance = MathUtil.inputModulus(
                            driveToPoseRotationGoal.position - measurement,
                            -errorBound,
                            errorBound);
                    double setpointMinDistance = MathUtil.inputModulus(
                            rotationState.position - measurement, -errorBound, errorBound);

                    // Recompute the profile goal with the smallest error,
                    // thus giving the shortest path. The goal
                    // may be outside the input range after this operation,
                    // but that's OK because the controller
                    // will still go there and report an error of zero. In
                    // other words, the setpoint only needs to
                    // be offset from the measurement by the input range
                    // modulus; they don't need to be equal.
                    driveToPoseRotationGoal.position = goalMinDistance + measurement;
                    rotationState.position = setpointMinDistance + measurement;

                    var rotSetpoint = driveToPoseRotationProfile.calculate(
                            0.02, rotationState, driveToPoseRotationGoal);
                    rotationState.position = rotSetpoint.position;
                    rotationState.velocity = rotSetpoint.velocity;

                    var startPose = initial.inner;

                    var interpTrans = goal.inner
                            .getTranslation()
                            .interpolate(
                                    startPose.getTranslation(), setpoint.position / distance.inner);

                    if (atDriveToPosePose.getAsBoolean()) {
                        setControl(pathApplyRobotSpeeds.withSpeeds(new ChassisSpeeds()));
                    } else {
                        followTrajectory(DriveUtil.sample(
                                interpTrans,
                                new Rotation2d(rotationState.position),
                                normDirStartToEnd.inner.getX() * setpoint.velocity,
                                normDirStartToEnd.inner.getY() * setpoint.velocity,
                                rotationState.velocity));
                    }
                }))
                .until(atDriveToPosePose.debounce(.1))
                .finallyDo(() -> setControl(pathApplyRobotSpeeds.withSpeeds(new ChassisSpeeds())));

        return command.withName("drive/driveToPoseCommand");
    }
}
