
package frc.robot;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj centerShoot = new ChoreoTraj(
	    "centerShoot",
	    OptionalInt.empty(),
	    0.7103,
	    new Pose2d(3.573, 4.035, Rotation2d.fromRadians(0)),
	    new Pose2d(2.268, 4.035, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj rightShoot = new ChoreoTraj(
	    "rightShoot",
	    OptionalInt.empty(),
	    1.42547,
	    new Pose2d(3.573, 0.624, Rotation2d.fromRadians(0)),
	    new Pose2d(3.091, 2.911, Rotation2d.fromRadians(0.679))
	);
	public static final ChoreoTraj leftShoot = new ChoreoTraj(
	    "leftShoot",
	    OptionalInt.empty(),
	    1.52505,
	    new Pose2d(3.573, 7.452, Rotation2d.fromRadians(0)),
	    new Pose2d(2.934, 5.167, Rotation2d.fromRadians(-0.602))
	);
	public static final ChoreoTraj doubleReload = new ChoreoTraj(
	    "doubleReload",
	    OptionalInt.empty(),
	    7.91458,
	    new Pose2d(3.595, 4.514, Rotation2d.fromRadians(0)),
	    new Pose2d(2.92, 4.702, Rotation2d.fromRadians(-0.269))
	);
	public static final ChoreoTraj leftSingleReload = new ChoreoTraj(
	    "leftSingleReload",
	    OptionalInt.empty(),
	    4.55988,
	    new Pose2d(3.582, 4.537, Rotation2d.fromRadians(0)),
	    new Pose2d(2.968, 4.57, Rotation2d.fromRadians(-0.273))
	);
	public static final ChoreoTraj rightSingleReload = new ChoreoTraj(
	    "rightSingleReload",
	    OptionalInt.empty(),
	    4.4285,
	    new Pose2d(3.582, 3.591, Rotation2d.fromRadians(0)),
	    new Pose2d(3.017, 3.226, Rotation2d.fromRadians(0.438))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("centerShoot", centerShoot),
		Map.entry("rightShoot", rightShoot),
		Map.entry("leftShoot", leftShoot),
		Map.entry("doubleReload", doubleReload),
		Map.entry("leftSingleReload", leftSingleReload),
		Map.entry("rightSingleReload", rightSingleReload)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
